#ifndef DEFINES_H_
#define DEFINES_H_


#define PLOP_APPLICATION_FULLNAME "Plop! reader"
#define PLOP_APPLICATION_SHORTNAME "Plop!R"

#define PLOP_VERSION_STR "v0.3.1"
#define PLOP_VERSION_NUM 5
#define PLOP_WEBSITE_URL "http://plop-reader.pascal-martin.fr"
#define PLOP_OPENSOURCE_URL "https://github.com/pmartin/plop-reader"

// On a TL3: /mnt/ext1/system/usr/share/plop-reader
#define PLOP_BASE_DIRECTORY USERDATA "/share/plop-reader"
#define PLOP_ENTRIES_CONTENT_DIRECTORY PLOP_BASE_DIRECTORY "/entries"
#define PLOP_ENTRIES_EPUB_DIRECTORY PLOP_BASE_DIRECTORY "/entries-epub"
#define PLOP_ENTRIES_IMAGES_DIRECTORY PLOP_BASE_DIRECTORY "/images"

#define PLOP_ASSETS_VERSION "1"
#define PLOP_ENTRIES_ASSETS_DIRECTORY PLOP_BASE_DIRECTORY "/assets"
#define PLOP_ICON_SYNC_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/sync.png"
#define PLOP_ICON_CLOSE_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/close.png"
#define PLOP_ICON_MENU_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/menu.png"
#define PLOP_ICON_HELP_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/help.png"
#define PLOP_ICON_WARNING_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/warning.png"
#define PLOP_ICON_UNREAD_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/unread.png"
#define PLOP_ICON_ARCHIVED_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/archived.png"
#define PLOP_ICON_STARRED_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/starred.png"
#define PLOP_ICON_EPUB_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/epub.png"
#define PLOP_ICON_HTML_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/html.png"
#define PLOP_ICON_SMALL_CLOCK_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/small_clock.png"
#define PLOP_ICON_SMALL_EVENT_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/small_event.png"
#define PLOP_ICON_SMALL_EPUB_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/small_epub.png"
#define PLOP_ICON_SMALL_HTML_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/small_html.png"
#define PLOP_ICON_SMALL_STARRED_PATH PLOP_ENTRIES_ASSETS_DIRECTORY "/small_starred.png"

#define PLOP_MAX_NUMBER_OF_ENTRIES_TO_FETCH_FROM_SERVER 200

#define PLOP_THUMBNAIL_MAX_WIDTH 128

#endif /* DEFINES_H_ */
